# Learning Numpy

In [1]:
import numpy as np

### Creating Arrays

<strong><ins>All arrays mentioned here are numpy arrays as long as opposite is not mentioned</ins></strong> please solve the problems with this knowledge.

Create an array in size of 4*3 and assing it to arr variable 

In [5]:
arr = np.zeros((4,3))

Create an array with elements from 0 to 15 (both inclusive) and assing it to arr2 variable   
Then print the shape of the arr2  
copy the arr2 to arr2_copy  
print arr2, arr2_copy   
Change its shape to 4*4 and assign to itself   
print arr2, arr2_copy again    

In [24]:
arr2 = np.arange(16)
arr2_copy = arr2.copy()

In [25]:
print(arr2.shape)

(16,)


In [26]:
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [27]:
arr2 = arr2.reshape(4,4)

In [28]:
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [29]:
print(arr2_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### Some Functions 

##### How many dimentions there are in arr2 variable? 

In [34]:
arr2.ndim

2

##### Describe the number of rows and columns in arr2 variable 

In [37]:
arr2.shape

(4, 4)

##### How many elements there are in arr2 variable?

In [38]:
arr2.size

16

##### Print the data type of arr2

In [39]:
arr2.dtype

dtype('int32')

#### Print the data location in the memory

In [77]:
arr2.data

### Some Statistics About the Arrays

#### Show 50th percentile of arr2

In [78]:
np.percentile(arr2,50)

7.5

#### Show mean of arr2 elements

In [79]:
np.mean(arr2)

7.5

#### Show median of arr2 elements

In [80]:
np.median(arr2)

7.5

##### Create one dimensional normally distrubuted array with mean 3 standard deviation is 4 and has elements of 100

In [34]:
from numpy import random

In [81]:
s = np.random.normal(loc=3, scale=4, size=100)

#### Install matplotlib library for ploting purposes and then plot the s 
- search to find how to do

In [91]:
import matplotlib.pyplot as plt

plt.hist(s, density=False)
plt.show()


____

# Learning Pandas

##### Read the airline safety data assign to df variable and print first 5 rows with pandas function

In [93]:
import pandas as pd 

In [102]:
df = pd.read_csv('numpy-pandas-exercises/airline_safety_data.csv')

In [103]:
df.head(n=5)

airline  avail_seat_km_per_week  incidents_85_99  \
0             Aer Lingus               320906734                2   
1              Aeroflot*              1197672318               76   
2  Aerolineas Argentinas               385803648                6   
3            Aeromexico*               596871813                3   
4             Air Canada              1865253802                2   

   fatal_accidents_85_99  fatalities_85_99  incidents_00_14  \
0                      0                 0                0   
1                     14               128                6   
2                      0                 0                1   
3                      1                64                5   
4                      0                 0                2   

   fatal_accidents_00_14  fatalities_00_14  
0                      0                 0  
1                      1                88  
2                      0                 0  
3                      0                 0  
4                      0                 0

##### print last 5 rows with pandas function

In [114]:
df.tail(n=5)

airline  avail_seat_km_per_week  incidents_85_99  \
51       United / Continental*              7139291291               19   
52  US Airways / America West*              2455687887               16   
53            Vietnam Airlines               625084918                7   
54             Virgin Atlantic              1005248585                1   
55             Xiamen Airlines               430462962                9   

    fatal_accidents_85_99  fatalities_85_99  incidents_00_14  \
51                      8               319               14   
52                      7               224               11   
53                      3               171                1   
54                      0                 0                0   
55                      1                82                2   

    fatal_accidents_00_14  fatalities_00_14  
51                      2               109  
52                      2                23  
53                      0                 0  
54                      0                 0  
55                      0                 0

##### Show shape of df

In [116]:
df.shape


(56, 8)

##### Show descriptive statistics of df

In [123]:
df.describe(include='all')

airline  avail_seat_km_per_week  incidents_85_99  \
count           56            5.600000e+01        56.000000   
unique          56                     NaN              NaN   
top     Aer Lingus                     NaN              NaN   
freq             1                     NaN              NaN   
mean           NaN            1.384621e+09         7.178571   
std            NaN            1.465317e+09        11.035656   
min            NaN            2.593733e+08         0.000000   
25%            NaN            4.740362e+08         2.000000   
50%            NaN            8.029089e+08         4.000000   
75%            NaN            1.847239e+09         8.000000   
max            NaN            7.139291e+09        76.000000   

        fatal_accidents_85_99  fatalities_85_99  incidents_00_14  \
count               56.000000         56.000000        56.000000   
unique                    NaN               NaN              NaN   
top                       NaN               NaN              NaN   
freq                      NaN               NaN              NaN   
mean                 2.178571        112.410714         4.125000   
std                  2.861069        146.691114         4.544977   
min                  0.000000          0.000000         0.000000   
25%                  0.000000          0.000000         1.000000   
50%                  1.000000         48.500000         3.000000   
75%                  3.000000        184.250000         5.250000   
max                 14.000000        535.000000        24.000000   

        fatal_accidents_00_14  fatalities_00_14  
count               56.000000         56.000000  
unique                    NaN               NaN  
top                       NaN               NaN  
freq                      NaN               NaN  
mean                 0.660714         55.517857  
std                  0.858684        111.332751  
min                  0.000000          0.000000  
25%                  0.000000          0.000000  
50%                  0.000000          0.000000  
75%                  1.000000         83.250000  
max                  3.000000        537.000000

#### Show df column informations

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   airline                 56 non-null     object
 1   avail_seat_km_per_week  56 non-null     int64 
 2   incidents_85_99         56 non-null     int64 
 3   fatal_accidents_85_99   56 non-null     int64 
 4   fatalities_85_99        56 non-null     int64 
 5   incidents_00_14         56 non-null     int64 
 6   fatal_accidents_00_14   56 non-null     int64 
 7   fatalities_00_14        56 non-null     int64 
dtypes: int64(7), object(1)
memory usage: 3.6+ KB


#### Select companies and incidents_85_99 with incidents_85_99 is less than 10

In [141]:
df[df['incidents_85_99']<10][['airline','incidents_85_99']]

airline  incidents_85_99
0               Aer Lingus                2
2    Aerolineas Argentinas                6
3              Aeromexico*                3
4               Air Canada                2
6               Air India*                2
7         Air New Zealand*                3
8         Alaska Airlines*                5
9                 Alitalia                7
10      All Nippon Airways                3
12       Austrian Airlines                1
13                 Avianca                5
14        British Airways*                4
15         Cathay Pacific*                0
17                  Condor                2
18                    COPA                3
20                Egyptair                8
21                   El Al                1
23                 Finnair                1
25                Gulf Air                1
26       Hawaiian Airlines                0
27                  Iberia                4
28          Japan Airlines                3
29           Kenya Airways                2
30                    KLM*                7
32            LAN Airlines                3
33              Lufthansa*                6
34       Malaysia Airlines                3
35  Pakistan International                8
36     Philippine Airlines                7
37                 Qantas*                1
38         Royal Air Maroc                5
39                    SAS*                5
40           Saudi Arabian                7
41      Singapore Airlines                2
42           South African                2
43      Southwest Airlines                1
44   Sri Lankan / AirLanka                2
45                  SWISS*                2
46                    TACA                3
47                     TAM                8
48      TAP - Air Portugal                0
49            Thai Airways                8
50        Turkish Airlines                8
53        Vietnam Airlines                7
54         Virgin Atlantic                1
55         Xiamen Airlines                9

#### Group companies by first letter(lower) and take the mean incidents_85_99 and make it a dataframe again 

In [162]:
df['firstletter'] = df['airline'].astype(str).str[0]
firsletter=df.groupby('firstletter').mean()['incidents_85_99']

C:\Users\Enis Mert Kiriş\AppData\Local\Temp\ipykernel_13232\3170292552.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  firsletter=df.groupby('firstletter').mean()['incidents_85_99']


In [67]:
_

airline_fist_letter  incidents_85_99
0                    a        10.714286
1                    b         4.000000
2                    c         4.250000
3                    d        24.000000
4                    e        11.333333
5                    f         1.000000
6                    g         5.500000
7                    h         0.000000
8                    i         4.000000
9                    j         3.000000
10                   k         7.000000
11                   l         4.500000
12                   m         3.000000
13                   p         7.500000
14                   q         1.000000
15                   r         5.000000
16                   s         3.000000
17                   t         5.400000
18                   u        17.500000
19                   v         4.000000
20                   x         9.000000